"""Infer a Pydantic schema from a sample JSON object."""
from __future__ import annotations

from typing import Any


def _infer_field_type(value: Any) -> str:
    """Return a Python type annotation string for a field value."""
    if value is None:
        return "Optional[str]"
    if isinstance(value, bool):
        return "bool"
    if isinstance(value, int):
        return "int"
    if isinstance(value, float):
        return "float"
    if isinstance(value, str):
        return "str"
    if isinstance(value, list):
        if not value:
            return "list[Any]"
        first = value[0]
        if isinstance(first, bool):
            elem = "bool"
        elif isinstance(first, int):
            elem = "int"
        elif isinstance(first, float):
            elem = "float"
        elif isinstance(first, str):
            elem = "str"
        else:
            return "list[Any]"
        # Check that all elements are the same type (ignoring bools as ints)
        for item in value[1:]:
            if type(item) is not type(first):
                return "list[Any]"
        return f"list[{elem}]"
    if isinstance(value, dict):
        return "dict[str, Any]"
    return "Any"


def infer_schema_source(class_name: str, sample: dict[str, Any]) -> str:
    """Return a Python source string defining a pydantic.BaseModel subclass
    whose fields match the keys and inferred types of *sample*.

    Inference rules (applied per field value):
        - str   → str
        - int   → int
        - float → float
        - bool  → bool
        - list  → list[<inferred element type>] (list[Any] if empty or mixed)
        - dict  → dict[str, Any]
        - None  → Optional[str] (conservative fallback)
        - anything else → Any

    The returned source string includes the necessary imports.
    """
    field_types: dict[str, str] = {k: _infer_field_type(v) for k, v in sample.items()}

    needs_any = any("Any" in t for t in field_types.values())
    needs_optional = any(t.startswith("Optional") for t in field_types.values())

    typing_names: list[str] = []
    if needs_any:
        typing_names.append("Any")
    if needs_optional:
        typing_names.append("Optional")

    lines: list[str] = [
        "# Auto-generated by: pyconveyor schema infer",
        "# Review and refine before committing to production.",
        "from __future__ import annotations",
        "",
    ]

    if typing_names:
        lines.append(f"from typing import {', '.join(sorted(typing_names))}")
        lines.append("")

    lines += [
        "from pydantic import BaseModel",
        "",
        "",
        f"class {class_name}(BaseModel):",
    ]

    if not field_types:
        lines.append("    pass")
    else:
        for fname, ftype in field_types.items():
            lines.append(f"    {fname}: {ftype}")

    lines.append("")
    return "\n".join(lines)
