"""Tests for pyconveyor.infer: infer_schema_source."""
from __future__ import annotations

import pytest
from pydantic import BaseModel

from pyconveyor.infer import infer_schema_source


class TestInferSchemaSource:
    def test_all_primitive_types(self):
        sample = {
            "title": "hello",
            "count": 5,
            "score": 3.14,
            "active": True,
        }
        src = infer_schema_source("MySchema", sample)
        assert "title: str" in src
        assert "count: int" in src
        assert "score: float" in src
        assert "active: bool" in src

    def test_none_field_produces_optional_str(self):
        src = infer_schema_source("MySchema", {"name": None})
        assert "Optional[str]" in src
        assert "from typing import" in src
        assert "Optional" in src

    def test_empty_list_produces_list_any(self):
        src = infer_schema_source("MySchema", {"items": []})
        assert "list[Any]" in src

    def test_list_of_strings(self):
        src = infer_schema_source("MySchema", {"tags": ["a", "b"]})
        assert "tags: list[str]" in src

    def test_list_of_ints(self):
        src = infer_schema_source("MySchema", {"nums": [1, 2, 3]})
        assert "nums: list[int]" in src

    def test_list_of_floats(self):
        src = infer_schema_source("MySchema", {"vals": [1.0, 2.5]})
        assert "vals: list[float]" in src

    def test_nested_dict_produces_dict_str_any(self):
        src = infer_schema_source("MySchema", {"meta": {"key": "val"}})
        assert "meta: dict[str, Any]" in src

    def test_output_is_valid_python(self):
        sample = {"title": "x", "score": 1, "tags": ["a"]}
        src = infer_schema_source("ArticleSchema", sample)
        compile(src, "<string>", "exec")  # should not raise

    def test_exec_produces_basemodel_subclass(self):
        sample = {"title": "x", "score": 1}
        src = infer_schema_source("MyModel", sample)
        ns: dict = {}
        exec(src, ns)  # noqa: S102
        cls = ns["MyModel"]
        assert issubclass(cls, BaseModel)
        inst = cls(title="hello", score=42)
        assert inst.title == "hello"
        assert inst.score == 42

    def test_any_not_in_imports_when_unneeded(self):
        src = infer_schema_source("MySchema", {"title": "x", "count": 1})
        # No list[Any], dict[str, Any], or None → Any not needed
        assert "Any" not in src

    def test_optional_not_in_imports_when_unneeded(self):
        src = infer_schema_source("MySchema", {"title": "x"})
        assert "Optional" not in src

    def test_optional_in_imports_when_needed(self):
        src = infer_schema_source("MySchema", {"x": None})
        assert "Optional" in src

    def test_any_in_imports_when_needed(self):
        src = infer_schema_source("MySchema", {"meta": {"k": "v"}})
        assert "Any" in src

    def test_header_comment_present(self):
        src = infer_schema_source("MySchema", {"x": "y"})
        assert "Auto-generated by: pyconveyor schema infer" in src

    def test_class_name_used(self):
        src = infer_schema_source("ArticleSchema", {"title": "x"})
        assert "class ArticleSchema(BaseModel):" in src

    def test_bool_inferred_correctly(self):
        src = infer_schema_source("MySchema", {"flag": False})
        assert "flag: bool" in src

    def test_mixed_list_produces_list_any(self):
        src = infer_schema_source("MySchema", {"items": [1, "two"]})
        assert "list[Any]" in src

    def test_list_of_bools(self):
        src = infer_schema_source("MySchema", {"flags": [True, False]})
        assert "flags: list[bool]" in src

    def test_list_of_dicts_produces_list_any(self):
        src = infer_schema_source("MySchema", {"records": [{"a": 1}, {"b": 2}]})
        assert "list[Any]" in src

    def test_empty_sample_produces_pass_body(self):
        src = infer_schema_source("Empty", {})
        assert "class Empty(BaseModel):" in src
        assert "pass" in src
